[package]
name = "viv"
version = "0.1.0"
authors = ["Alex Hamilton <alex.hamilton@ou.edu>"]

[features]
tui = ["termion"]
default = ["tui"]

[dependencies]
termion = { version = "1.5.1", optional = true }
rand = "0.5.4"
