[package]
name = "viv"
version = "0.1.0"
authors = ["Alex Hamilton <alex.hamilton@ou.edu>"]

[features]
tui = ["termion"]
web = ["stdweb"]
default = ["tui"]

[dependencies]
rand = "0.5.4"
termion = { version = "1.5.1", optional = true }
stdweb = { version = "0.4.8", optional = true }
